;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Movement.Idle",NewTagName="Status.Movement.Idle")
+GameplayTagRedirects=(OldTagName="Movement.Walk",NewTagName="Status.Movement.Gait.Walk")
+GameplayTagRedirects=(OldTagName="Movement.Run",NewTagName="Status.Movement.Gait.Run")
+GameplayTagRedirects=(OldTagName="Movement.Sprint",NewTagName="Status.Movement.Gait.Sprint")

