;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameplayCue.Action.Combat.Attack.Basic",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Action.Combat.Attack.ResetCombo",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Action.Combat.EquipWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Action.Combat.ToggleWeapon",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Action.Combat.UnequipWeapon",DevComment="")

