#pragma once

#include "NativeGameplayTags.h"

namespace  CBGameplayTags
{
	/** Input Tags. */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Move)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Look)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Sprint)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Walk)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Camera_Zoom)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Combat_Attack_Basic)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Combat_EquipWeapon)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Action_Combat_UnequipWeapon)

	/** Item Tags. */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Sword)
	
	/** Status Tags. */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Combat_InCombat)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Movement_Overridden)
	
	/** Event Tags. (애님노티파이 등 태그 이벤트) */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_EquipWeapon)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Combat_UnequipWeapon)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Action_EndAbility)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Action_CheckInput)
	
	/** Movement Tags. (이동 상태) */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Idle)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Walk)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Run)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Sprint)

	/** Data Tags. (SetByCaller 전용) */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Movement_Speed)

	/** Ability Tags. */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_Attack_Basic)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_EquipWeapon)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Combat_UnequipWeapon)

	/** Action Tags. (액션에 맞는 몽타주 재생에 사용) */
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_Attack)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_Attack_Basic)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_Block)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_Hit)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_Skill)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_EquipWeapon)
	CHAINBURST_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Combat_UnequipWeapon)
}
